SRC_NAME = hxcli
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/hx-cli /usr/bin/hx-cli
	$(ROMFSINST) -p +x $(THISDIR)/hx.sh /usr/bin/hx.sh
	$(ROMFSINST) -p +x $(THISDIR)/hxzn.sh /usr/bin/hxzn.sh
