SRC_NAME = bafa
THISDIR = $(shell pwd)

all:

extract_test:

config_test:
clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/bafa.sh /usr/bin/bafa.sh
	$(ROMFSINST) -p +x $(THISDIR)/bafares.sh /usr/bin/bafares.sh
	$(ROMFSINST) -p +x $(THISDIR)/stdoutsubc /usr/bin/stdoutsubc
