SRC_NAME = etink
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/etink.sh /usr/bin/etink.sh
	$(ROMFSINST) -p +x $(THISDIR)/easytier.sh /usr/bin/easytier.sh
	$(ROMFSINST) -p +x $(THISDIR)/easytier-core /usr/bin/easytier-core
	$(ROMFSINST) -p +x $(THISDIR)/easytier-cli /usr/bin/easytier-cli
